#!/bin/bash

# On-board LEDs control

LED_TIMEOUT=0.2
LED_PATH=/sys/class/bone_gpios

LED_ON ()
{
    echo 1 > $1/value
}

LED_OFF ()
{
    echo 0 > $1/value
}

LED_INIT ()
{
    for (( i=0; i<=3; i++ ))
    do 
        LED=$LED_PATH/userled$i:gpio1.2$(($i+1))
        if ! [ -e $LED ]; then
            echo "File $LED not found"
            exit
        fi
        LED_OFF $LED
    done
}

LED_INIT
sleep 0.5

while true
do
    for (( i=0; i<=3; i++ ))
    do
        LED=$LED_PATH/userled$i:gpio1.2$((i+1))
        LED_ON $LED
        sleep $LED_TIMEOUT
    done
    for (( i=3; i>=0; i-- ))
    do
        LED=$LED_PATH/userled$i:gpio1.2$((i+1))
        LED_OFF $LED
        sleep $LED_TIMEOUT
    done
done

